version: "3.8"
services:
  stun:
    image: ich777/stun-turn-server
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
  receiver:
    build: containers/receiver
    image: johnson163/pandia_receiver
    depends_on:
      - stun
    cap_add:
      - NET_ADMIN
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WEBRTC_CONNECT="stun:stun:3478"
    restart: always
    expose:
      # - "9998-9999:9998-9999"
      - "1-65535/udp"
    ports:
      - "9998-9999:9998-9999"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  sender_base:
    build: containers/sender_base
    image: johnson163/pandia_sender_base
  sender:
    build: containers/sender
    image: johnson163/pandia_sender
    depends_on:
      - stun
      - receiver
      - sender_base
    cap_add:
      - NET_ADMIN
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RL_SERVER=195.148.127.234
      - PRINT_STEP=True
      # - PRINT_SENDER_LOG=True
    restart: always
    expose:
      - "1-65535/udp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
