version: "3.8"
services:
  sender:
    build: containers/sender
    image: johnson163/pandia_sender
    command: ["/app/peerconnection_client_headless"]
  receiver:
    build: containers/receiver
    image: johnson163/pandia_receiver
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "9999:9999"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
