services:
  sender_base:
    build: containers/sender_base
    image: johnson163/pandia_sender_base
  emulator:
    build: containers/emulator
    image: johnson163/pandia_emulator
    depends_on:
      - sender_base
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: always
  receiver:
    build: containers/receiver
    image: johnson163/pandia_receiver
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: always
    expose:
      - "9998-9999:9998-9999"
      - "1-65535/udp"
  sender:
    build: containers/sender
    image: johnson163/pandia_sender
    depends_on:
      - receiver
      - sender_base
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: always
    expose:
      - "1-65535/udp"
